### ISSUE TITLE
endpoint is outdated

### ISSUE THREAD

**Issue by AmauryVanEspen** [brbkaffe/europass-server#11]
Hi @bjornsnoen 
it seems the endpoint : https://europass.cedefop.europa.eu/nb is outdated
is the project still running ?
Thank you
Amaury

**Comment by bjornsnoen** [comment]
Hi! Sorry I haven't needed to use this in a long time, but I knew Europass were working on a new version of their service, so I'm not surprised that this happened, though I am sorry I won't be able to help. I'll add a notice to the repo that it only supports old exports from europass and put the repository in archive mode.
Again, I apologize for not being able to help.

**Comment by bjornsnoen** [comment]
Hey so I updated the repo and you can now use modern europass pdf files, refer to the README for instructions.
